[package]
name = "hangman"
version = "0.1.0"
authors = ["Kesavan Yogeswaran"]
edition = "2021"

[dependencies]
cortex-m = "0.7.3"
cortex-m-rt = "0.7.0"
rtt-target = { version = "0.3.1", features = ["cortex-m"] }
nrf52840-hal = { version = "0.16", features = ["rt"] }
panic-abort = "0.3"

[dependencies.embedded-hal]
version = "0.2.3"
features = ["unproven"]
